<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SparepartSeeder extends Seeder
{
    public function run(): void
    {
        // Kosongkan tabel dulu
        DB::table('spareparts')->truncate();

        $spareparts = [
            [
                'name' => 'LCD iPhone 11',
                'compatible_for' => 'iPhone 11, iPhone 11 Pro',
                'price' => 850000,
                'stock' => 15,
                'warranty' => '30 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LCD iPhone 12',
                'compatible_for' => 'iPhone 12, iPhone 12 Mini',
                'price' => 1200000,
                'stock' => 10,
                'warranty' => '30 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LCD Samsung A52',
                'compatible_for' => 'Samsung Galaxy A52, A52s',
                'price' => 650000,
                'stock' => 20,
                'warranty' => '30 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LCD Samsung S21',
                'compatible_for' => 'Samsung Galaxy S21, S21+',
                'price' => 1500000,
                'stock' => 8,
                'warranty' => '30 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baterai iPhone 11',
                'compatible_for' => 'iPhone 11',
                'price' => 350000,
                'stock' => 25,
                'warranty' => '14 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baterai iPhone 12',
                'compatible_for' => 'iPhone 12, iPhone 12 Mini',
                'price' => 400000,
                'stock' => 18,
                'warranty' => '14 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baterai Samsung A52',
                'compatible_for' => 'Samsung Galaxy A52, A52s',
                'price' => 280000,
                'stock' => 30,
                'warranty' => '14 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kamera Belakang iPhone 11',
                'compatible_for' => 'iPhone 11',
                'price' => 450000,
                'stock' => 12,
                'warranty' => '14 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kamera Belakang Samsung A52',
                'compatible_for' => 'Samsung Galaxy A52',
                'price' => 320000,
                'stock' => 3,
                'warranty' => '14 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Connector Charger iPhone',
                'compatible_for' => 'iPhone X, XS, 11, 12',
                'price' => 180000,
                'stock' => 40,
                'warranty' => '7 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Connector Charger Type-C',
                'compatible_for' => 'Samsung, Xiaomi, Oppo, Vivo',
                'price' => 120000,
                'stock' => 50,
                'warranty' => '7 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Speaker iPhone 11',
                'compatible_for' => 'iPhone 11, iPhone 11 Pro',
                'price' => 200000,
                'stock' => 0,
                'warranty' => '7 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LCD Xiaomi Redmi Note 10',
                'compatible_for' => 'Xiaomi Redmi Note 10, Note 10S',
                'price' => 450000,
                'stock' => 22,
                'warranty' => '30 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baterai Xiaomi Redmi Note 10',
                'compatible_for' => 'Xiaomi Redmi Note 10',
                'price' => 200000,
                'stock' => 35,
                'warranty' => '14 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LCD Oppo A54',
                'compatible_for' => 'Oppo A54, A55',
                'price' => 400000,
                'stock' => 4,
                'warranty' => '30 Hari',
                'image' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('spareparts')->insert($spareparts);
    }
}